apiVersion: v1
kind: Namespace
metadata:
  name: staticns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  namespace: staticns
spec:
  selector:
    matchLabels:
      app: static
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 783911693980.dkr.ecr.ap-south-1.amazonaws.com/staticweb:number
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-svc
  namespace: staticns
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ingress
 namespace: staticns
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: app4k8s.motupatlurayachoty.xyz
   http:
     paths:
     - path:
       backend:
         serviceName: static-svc
         servicePort: 80
---
